nav:
  - ğŸ¡ ä¸»é¡µ: # ä¸»é¡µ/
    - index.md
    - â¤ï¸ æˆ‘å’Œæœ‹å‹ä»¬ï¼: ä¸»é¡µ/about.md
    - ğŸ“† æœ€è¿‘æ›´æ–°: recent.md
    # - ğŸŒˆ é¢œè‰²ä¸»é¢˜ & å¤œé—´æ¨¡å¼: ä¸»é¡µ/theme.md
  - C++:
    - cpp/index.md
    - ğŸ‰C++ å­¦ä¹ è®°å½•:
      - cpp/cpp_restart/index.md
      - æœ‹è¾ˆè¾…å­¦ slides:
        - Week1 C++ çš„è¯ç”Ÿä¸é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡: https://xuan-insr.github.io/slides/cpp/1_birth_and_oop/
      - æ­£æ–‡ï¼:
        - 1 C++ çš„è¯ç”Ÿ: cpp/cpp_restart/1_birth.md
        - 2 ç¼–ç¨‹èŒƒå¼: cpp/cpp_restart/2_paradigm.md
        - 3 é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡: cpp/cpp_restart/3_oop.md
        - 4 ç±» (I) - å®šä¹‰ã€æˆå‘˜ã€æ„é€ ã€ææ„: cpp/cpp_restart/4_class_1.md
        - 5 ç±» (II) - æ‹·è´æ„é€ ä¸æ‹·è´èµ‹å€¼: cpp/cpp_restart/5_class_2.md
        - 6 ç±» (III) - è½¬æ¢æ„é€ å‡½æ•°: cpp/cpp_restart/6_class_3.md
        - 7 ç±» (IV) - const å’Œ static æˆå‘˜: cpp/cpp_restart/7_class_4.md
        - 8 ç±» (V) - ç»§æ‰¿ä¸æŠ½è±¡ç±»ã€è®¿é—®æ§åˆ¶: cpp/cpp_restart/8_class_5.md
        - 9 æ¨¡æ¿: cpp/cpp_restart/9_template.md
        - 10 STL: cpp/cpp_restart/10_stl.md
        - 11 å³å€¼å¼•ç”¨å’Œç§»åŠ¨è¯­ä¹‰: cpp/cpp_restart/11_move_semantics.md
        - 12 ç±» (VI) - ç§»åŠ¨æ„é€ ä¸ç§»åŠ¨èµ‹å€¼: cpp/cpp_restart/12_class_6.md
        - 13 namespace: cpp/cpp_restart/13_namespace.md
        - 14 exception: cpp/cpp_restart/14_exception.md
      - A é™„å½•:
        - å£°æ˜ä¸å®šä¹‰: cpp/cpp_restart/appendix/decl_and_def.md
        - inline å‡½æ•°: cpp/cpp_restart/appendix/inline_functions.md
        - å‡½æ•°é»˜è®¤å‚æ•°ä¸é‡è½½: cpp/cpp_restart/appendix/func_overload.md
        - è¿ç®—ç¬¦é‡è½½: cpp/cpp_restart/appendix/operator_overload.md
        - å¼•ç”¨: cpp/cpp_restart/appendix/references.md
        - I/O stream: cpp/cpp_restart/appendix/iostream.md
        - copy elision: cpp/cpp_restart/appendix/copy_elision.md
        - ç±»å‹è½¬æ¢: cpp/cpp_restart/appendix/cast.md
        - bool: cpp/cpp_restart/appendix/bool.md
        - auto: cpp/cpp_restart/appendix/auto.md
        - æœªå®šä¹‰è¡Œä¸º: cpp/cpp_restart/appendix/undefined_behavior.md
        - std::string: cpp/cpp_restart/appendix/string.md
        - æ™ºèƒ½æŒ‡é’ˆ: cpp/cpp_restart/appendix/smart_pointers.md
        - lambda: cpp/cpp_restart/appendix/lambda.md
      - B æ€»ç»“:
        - member initializer lists: cpp/cpp_restart/summaries/member_init_lists.md
      - ä¸€äº›ç¬”è®°å’Œ TODO:
        - é›¶æ•£å†…å®¹è®°å½•: cpp/cpp_restart/notes/notes.md
        - The Design and Evaluation of C++ é˜…è¯»è®°å½•: cpp/cpp_restart/notes/dne_notes.md
        - C++ è¯­è¨€æ ‡å‡†é˜…è¯»è®°å½•: cpp/cpp_restart/notes/std_notes.md
        - C++ Core Guidelines é˜…è¯»è®°å½•: cpp/cpp_restart/notes/guideline_notes.md
        - Bjarne Stroustrup's FAQ é˜…è¯»è®°å½•: cpp/cpp_restart/notes/bs_faq_notes.md
    - å¿«é€Ÿå…¥é—¨ C++ å†™é¢˜: cpp/cpp_for_contests.md
    #- C++ é¢å‘å¯¹è±¡: 404.md
    - C++ çŸ¥è¯†è¡¥å……:
      - ç†è§£ STL â€”â€” è¿­ä»£å™¨ä¸å‡½æ•°å¯¹è±¡: cpp/ç†è§£ STL - è¿­ä»£å™¨ä¸å‡½æ•°å¯¹è±¡.md
  - PL & ç¼–è¯‘: 
    - pl/index.md
    - ç¼–ç¨‹è¯­è¨€åŸç†: 
      - pl/ppl_notes/index.md
      - æˆ‘åœ¨ PPL 2022 Final å‡ºçš„å¤ä¹ é¢˜: pl/ppl_notes/0_PPL_Final_Problem1.md
      - Part I - Judgments and Rules | åˆ¤æ–­ä¸è§„åˆ™:
        - 1 æŠ½è±¡è¯­æ³•: pl/ppl_notes/1_Abstract_Syntax.md
        - 2 å½’çº³å®šä¹‰: pl/ppl_notes/2_Inductive_Definition.md
        - 3 å‡è¨€åˆ¤æ–­ä¸ä¸€èˆ¬æ€§åˆ¤æ–­: pl/ppl_notes/3_Hypothetical_and_General_Judgments.md
      - Part II - Statics and Dynamics | é™æ€è¯­ä¹‰å’ŒåŠ¨æ€è¯­ä¹‰:
        - 4 é™æ€è¯­ä¹‰: pl/ppl_notes/4_Statics.md
        - 5 åŠ¨æ€è¯­ä¹‰: pl/ppl_notes/5_Dynamics.md
        - 6 ç±»å‹å®‰å…¨: pl/ppl_notes/6_Type_Safety.md
      - Part III - Total Functions | å…¨å‡½æ•°:
        - 8 å‡½æ•°å®šä¹‰å’Œå€¼: pl/ppl_notes/8_Func_Def_and_Val.md
        - 9 é«˜é˜¶é€’å½’çš„ç³»ç»Ÿ T: pl/ppl_notes/9_Sys_T_of_Higher_Order_Recursion.md
      - Part IV - Finite Data Types | æœ‰é™æ•°æ®ç±»å‹:
        - 10 ç§¯ç±»å‹: pl/ppl_notes/10_product_types.md
        - 11 å’Œç±»å‹: pl/ppl_notes/11_sum_types.md
    - ç¼–è¯‘åŸç†: compile_principle/index.md
    - OCaml å…¥é—¨: https://www.yuque.com/xianyuxuan/coding/ocaml
  - æ ¸å¿ƒçŸ¥è¯†: 
    - æ ¸å¿ƒçŸ¥è¯†/index.md
    - æ“ä½œç³»ç»Ÿ:
      - 1 å†™åœ¨å‰é¢: æ ¸å¿ƒçŸ¥è¯†/os/I_overview/1_intro.md
      - Part.1 æ¦‚è¿°: æ ¸å¿ƒçŸ¥è¯†/os/I_overview/2_overview.md
      - Part.2 è¿›ç¨‹ç®¡ç†:
        - 3 è¿›ç¨‹: æ ¸å¿ƒçŸ¥è¯†/os/II_process_management/3_process.md
        - 4 è°ƒåº¦: æ ¸å¿ƒçŸ¥è¯†/os/II_process_management/4_sched.md
        - 5 çº¿ç¨‹: æ ¸å¿ƒçŸ¥è¯†/os/II_process_management/5_thread.md
      - Part.3 è¿›ç¨‹åŒæ­¥:
        - 6 åŒæ­¥åŠå…¶å·¥å…·: æ ¸å¿ƒçŸ¥è¯†/os/III_process_sync/6_sync_tools.md
        - 7 ç»å…¸åŒæ­¥é—®é¢˜: æ ¸å¿ƒçŸ¥è¯†/os/III_process_sync/7_sync_examples.md
        - 8 æ­»é”: æ ¸å¿ƒçŸ¥è¯†/os/III_process_sync/8_deadlocks.md
      - Part.4 å†…å­˜ç®¡ç†:
        - 9 ä¸»å­˜: æ ¸å¿ƒçŸ¥è¯†/os/IV_memory_management/9_main_memory.md
        - 10 è™šæ‹Ÿå†…å­˜: æ ¸å¿ƒçŸ¥è¯†/os/IV_memory_management/10_virtual_memory.md
      - Part.5 å­˜å‚¨ç®¡ç†:
        - 11 å¤§å®¹é‡å­˜å‚¨: æ ¸å¿ƒçŸ¥è¯†/os/V_storage_management/11_mass_storage.md
        - 12 I/O ç³»ç»Ÿ: æ ¸å¿ƒçŸ¥è¯†/os/V_storage_management/12_io_systems.md
      - Part.6 æ–‡ä»¶ç³»ç»Ÿ:
        - 13 æ–‡ä»¶ç³»ç»Ÿ: æ ¸å¿ƒçŸ¥è¯†/os/VI_file_system/13_fs_interface.md
        - 14 æ–‡ä»¶ç³»ç»Ÿå®ç°: æ ¸å¿ƒçŸ¥è¯†/os/VI_file_system/14_fs_impl.md
      - 15 æ€»ç»“: æ ¸å¿ƒçŸ¥è¯†/os/15_review.md
    - è®¡ç®—æœºç»„æˆ:
      - 1 å†™åœ¨å‰é¢: computer_organization/1_prelude.md
      - 2 Instructions: computer_organization/2_instructions.md
      - 3 Arithmetic: computer_organization/3_arithmetic.md
      - 4 Processor: computer_organization/4_processor.md
      - 5 Cache: computer_organization/5_cache.md
      - 6 I/O: computer_organization/6_IO.md
      - 2022 å›å¿†å·: computer_organization/å†å¹´å·.md
    - ç¼–è¯‘åŸç†:
      - compile_principle/index.md
      - I è¯æ³•åˆ†æ: compile_principle/1 Lexical Analysis.md
      - II è¯­æ³•åˆ†æ - è‡ªé¡¶å‘ä¸‹åˆ†æ: compile_principle/2 Parsing (I).md
      - III è¯­æ³•åˆ†æ - è‡ªåº•å‘ä¸Šåˆ†æ: compile_principle/3 Parsing (II).md
      - IV è¯­ä¹‰åˆ†æ: compile_principle/4 Semantic Analysis.md
      - V è¿è¡Œæ—¶ç¯å¢ƒ: compile_principle/5 Runtime Environment.md
      - VI ä»£ç ç”Ÿæˆ: compile_principle/6 Code Generation.md
    - æ•°å­¦ã€æ•°æ®ç»“æ„å’Œç®—æ³•: 
      - math_ds_algo/index.md
      - å…¥é—¨è·¯çº¿: math_ds_algo/getting_started.md
  - å®‰å…¨: 
    - å®‰å…¨/index.md
    - å¯†ç å­¦: https://www.yuque.com/xianyuxuan/coding/crypto
    - å¯†ç å­¦è¿›é˜¶: https://www.yuque.com/xianyuxuan/coding/advcrypto
    - è½¯ä»¶å®‰å…¨: https://www.yuque.com/xianyuxuan/coding/softwsec
    - ç½‘ç»œå®‰å…¨åŸç†ä¸å®è·µ: https://www.yuque.com/xianyuxuan/coding/netsec
    - ç³»ç»Ÿå®‰å…¨: https://www.yuque.com/xianyuxuan/coding/syssec
    - æ— çº¿ä¸ç‰©è”ç½‘å®‰å…¨åŸºç¡€: https://www.yuque.com/xianyuxuan/coding/wireless_iot
    - é¢å‘ä¿¡æ¯å®‰å…¨çš„ä¿¡å·å¤„ç†: https://www.yuque.com/xianyuxuan/coding/signal_processing
  - è¯­è¨€åŸºç¡€: è¯­è¨€åŸºç¡€/index.md
  - å…¶ä»–è¯¾ç¨‹: 
    - other_courses/index.md
    - è®¡ç®—ç†è®º: other_courses/theory_of_computation.md
  - æ‚é¡¹:
    - æ‚é¡¹/index.md
    - åšå®¢æ­å»ºè®°å½•: æ‚é¡¹/åšå®¢æ­å»ºè®°å½•.md
  - ç”Ÿæ´»:
    - ç”Ÿæ´»/index.md
    - è®¨é¥­å†ç¨‹:
      - ğŸ³ï¸â€ğŸŒˆ æ€»è§ˆ: interviews/overview.md
      - ğŸ˜• æ‹¼å¤šå¤š: interviews/pdd.md
      - ğŸ¤— ç¾å›¢: interviews/meituan.md
      - ğŸ¤” èš‚èš: interviews/mayi.md
      - ğŸ‘ åä¸º: interviews/huawei.md
      - ğŸ¥³ å­—èŠ‚: interviews/bytedance.md
      - ğŸ‘¨â€ğŸ’» é‡åŒ–ç›¸å…³: interviews/quant.md
      - å…¶ä»–: interviews/others.md
    # - å’¸é±¼æš„ä»Šå¤©åƒä»€ä¹ˆ: ç”Ÿæ´»/å’¸é±¼æš„ä»Šå¤©åƒä»€ä¹ˆ.md
    - æˆ‘éœ€è¦ä¸€ä¸ªå¤–ç½®å¤§è„‘: ç”Ÿæ´»/æˆ‘éœ€è¦ä¸€ä¸ªå¤–ç½®å¤§è„‘.md
    - å…³äºäº²å¯†å…³ç³»çš„ç¢ç¢å¿µ: ç”Ÿæ´»/äº²å¯†å…³ç³».md
    - 2022 å¹´ç»ˆæ€»ç»“: ç”Ÿæ´»/2022.md
    - å›é¡¾åœ¨ä¿¡å®‰çš„ä¸‰å¹´: ç”Ÿæ´»/å›é¡¾åœ¨ä¿¡å®‰çš„ä¸‰å¹´.md
    - æ¡Œæ¸¸: 
      - æ¡Œæ¸¸/index.md
      - é…ä»¶ç›¸å…³: æ¡Œæ¸¸/components.md
  
site_name: å’¸é±¼æš„çš„ä»£ç ç©ºé—´
site_url: https://xuan-insr.github.io/
repo_name: xuan-insr/å’¸é±¼æš„çš„ä»£ç ç©ºé—´
repo_url: https://github.com/xuan-insr/xuan-insr.github.io

theme:
  name: material
  logo: logo.ico
  favicon: logo.ico
  features:
    - navigation.tabs # ä¸€çº§å¯¼èˆªåœ¨æ¨ªç€çš„å¯¼èˆªæ 
    - content.code.annotate # å¯ä»¥åœ¨ä»£ç å—ä¸­å¢æ·»ç‚¹å‡»å±•ç¤ºçš„æ³¨é‡Šï¼Œå‚è§ https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - navigation.tracking # åœ°å€æ ä¸­çš„ URL ä¼šéšå½“å‰ä½ç½®å˜åŒ–ä¸ºå¯¹åº”å°èŠ‚çš„ URL
    - navigation.indexes # å°† index é¡µé¢ç›´æ¥é™„åˆ°å°èŠ‚åä¸Š
    - navigation.top # å›åˆ°é¡¶éƒ¨æŒ‰é’®
    # - navigation.sections # äºŒçº§å¯¼èˆªæ˜¯ç²—ä½“
    # - navigation.expand # å¯¼èˆªé»˜è®¤å±•å¼€
    - toc.follow # toc è·Ÿéš
    # - toc.integrate # æ–‡æ¡£ toc é›†æˆåˆ°æ€»ç›®å½•ä¸­ 
  language: 'zh'
  palette:
    primary: red
    scheme: default
  font:
    text: Noto Serif SC # Roboto
    code: Roboto Mono
  custom_dir: overrides # ç”¨æ¥æè¯„è®ºçš„ï¼Œå‚è€ƒ https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      # smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets: # å…è®¸å°†å…¶ä»–æ–‡ä»¶å†…å®¹æ’å…¥æ–‡ä»¶ï¼Œè¯­æ³•æ˜¯ --8<-- "filename.ext" ç­‰ï¼Œå‚è§ https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  analytics:
    provider: google
    property: G-JT9BRCXKJJ

# extra:
#   search:
#     language: 'jp'
#   pagetime: 'on'
  
copyright: 'æœ¬é¡µé¢çš„å…¨éƒ¨å†…å®¹åœ¨ <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> å’Œ <a href="https://github.com/zTrix/sata-license">SATA</a> åè®®ä¹‹æ¡æ¬¾ä¸‹æä¾›ï¼Œé™„åŠ æ¡æ¬¾äº¦å¯èƒ½åº”ç”¨'

extra_css:
  - 'from_oi_wiki/css/extra.css?v=13'
  - css/status.css

extra_javascript:
  - 'from_oi_wiki/js/extra.js'
  - js/mathjax.js # æ”¯æŒæ•°å­¦å…¬å¼ï¼Œref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # æ”¯æŒè¡¨æ ¼æ’åº
  - js/tablesort.js

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - statistics